CREATE TABLE IF NOT EXISTS uploads (
  id INTEGER NOT NULL PRIMARY KEY,
  device_id VARCHAR NOT NULL,
  filename VARCHAR NOT NULL,
  checksum VARCHAR NOT NULL,
  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP
)